### ISSUE TITLE
About the crosshairs code

### ISSUE THREAD

**Issue by aspphp** [sepremz/Valorant-TriggerBot-PixelColor#10]
First of all thank you very much for sharing the script, I would like to ask if there is a recommended crosshair code.Because I tested multiple crosshairs, the recognition wasn't very sensitive

**Comment by sepremz** [comment]
> First of all thank you very much for sharing the script, I would like to ask if there is a recommended crosshair code.Because I tested multiple crosshairs, the recognition wasn't very sensitive

Thank you! ye there's a lot of crosshairs just join our discord and you'll get them!
