### ISSUE TITLE
No Auto-Aim

### ISSUE THREAD

**Issue by xMqneyBagz** [sepremz/Valorant-TriggerBot-PixelColor#7]
It says in your V-2 that there is an "auto-aim" feature but when looking in the code and using the hotkey mentioned in the README there is not AUTOAIM features.

**Comment by xMqneyBagz** [comment]
Also your v3 BETA doesn't work, I looked through the code and it seems like it should but then again I'm no programmer.

**Comment by xMqneyBagz** [comment]
Understandable, it just said that the feature was implemented so I assumed it was. Thanks for the clarification.

**Comment by xMqneyBagz** [comment]
Also is it possible for you to add a GUI element the says which click mode is active like BURST FIRE ON ect.

**Comment by Naugustogi** [comment]
Will do.
